TRAIN_SIZE: 0.7                 # TRAIN_SIZE + VALIDATION_SIZE + TEST_SIZE === 1 !!!
VALIDATION_SIZE: 0.2            #
TEST_SIZE: 0.1                  #
AUGMENTATION: True              # Data augmentation
IMAGE_SIZE: 128                 #
BATCH_SIZE: 64                  # 
EPOCHS: 10                      # Number of epochs - model training iterations
LEARNING_RATE: 0.001            # Optimizer learning rate (step)
CHANNELS: 4                     # Convolution layer depth
KERNEL_SIZE_CL: 5               # Convolution layer filter size
OPTIMIZER: "Adam"               # Adam and SGD are only supported